name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm ci
          cd functions && npm ci
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        run: |
          # Función para verificar si el error es de cuota
          check_quota_error() {
            if [[ $1 == *"Quota exceeded"* ]]; then
              return 0
            fi
            return 1
          }
          
          # Intentar el despliegue hasta 3 veces
          for i in {1..3}; do
            echo "Intento de despliegue $i de 3..."
            if firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive; then
              echo "Despliegue exitoso en el intento $i"
              exit 0
            else
              ERROR_CODE=$?
              ERROR_MESSAGE=$(firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive 2>&1)
              
              if check_quota_error "$ERROR_MESSAGE"; then
                echo "Error de cuota detectado. Esperando 120 segundos antes del siguiente intento..."
                sleep 120
              else
                echo "Error no relacionado con cuota: $ERROR_MESSAGE"
                exit $ERROR_CODE
              fi
            fi
          done
          
          echo "Todos los intentos de despliegue fallaron"
          exit 1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Verify Deployment
        run: |
          echo "Verificando despliegue..."
          sleep 30
          curl -f https://us-central1-asistenteia-185c4.cloudfunctions.net/api/health || exit 1
          curl -f https://asistenteia.web.app || exit 1
          
      - name: Check Logs
        if: failure()
        run: |
          echo "Verificando logs de Firebase Functions..."
          firebase functions:log --only errors --token "${{ secrets.FIREBASE_TOKEN }}"
          echo "Verificando logs de Firebase Hosting..."
          firebase hosting:log --only errors --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 