name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Clean Install Dependencies
        run: |
          # Limpiar caché y módulos
          rm -rf node_modules
          rm -rf functions/node_modules
          rm -f package-lock.json
          rm -f functions/package-lock.json
          
          # Instalar dependencias
          npm install
          cd functions && npm install
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        run: |
          # Función para verificar si el error es de cuota
          check_quota_error() {
            if [[ $1 == *"Quota exceeded"* ]]; then
              return 0
            fi
            return 1
          }
          
          # Intentar el despliegue hasta 3 veces
          for i in {1..3}; do
            echo "Intento de despliegue $i de 3..."
            if firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive; then
              echo "Despliegue exitoso en el intento $i"
              exit 0
            else
              ERROR_CODE=$?
              ERROR_MESSAGE=$(firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive 2>&1)
              
              if check_quota_error "$ERROR_MESSAGE"; then
                echo "Error de cuota detectado. Esperando 120 segundos antes del siguiente intento..."
                sleep 120
              else
                echo "Error no relacionado con cuota: $ERROR_MESSAGE"
                exit $ERROR_CODE
              fi
            fi
          done
          
          echo "Todos los intentos de despliegue fallaron"
          exit 1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Verify Deployment
        run: |
          echo "Verificando despliegue..."
          sleep 60
          
          # Función para verificar la API con reintentos
          check_api() {
            for i in {1..3}; do
              echo "Verificando API (intento $i de 3)..."
              API_RESPONSE=$(curl -s https://us-central1-asistenteia-185c4.cloudfunctions.net/health)
              if [[ $API_RESPONSE == *"status"* ]]; then
                echo "API está funcionando correctamente"
                return 0
              fi
              echo "Esperando 30 segundos antes del siguiente intento..."
              sleep 30
            done
            return 1
          }
          
          # Verificar la API
          if ! check_api; then
            echo "Error: API no está respondiendo correctamente después de 3 intentos"
            exit 1
          fi
          
          # Verificar el hosting
          HOSTING_RESPONSE=$(curl -s https://asistenteia.web.app)
          if [[ $HOSTING_RESPONSE == *"<!DOCTYPE html>"* ]]; then
            echo "Hosting está funcionando correctamente"
          else
            echo "Error: Hosting no está respondiendo correctamente"
            exit 1
          fi
          
      - name: Check Logs
        if: failure()
        run: |
          echo "Verificando logs de Firebase Functions..."
          firebase functions:log --token "${{ secrets.FIREBASE_TOKEN }}"
          echo "Verificando logs de Firebase Hosting..."
          firebase hosting:log --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 